# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
ENABLE_LINTERS:
  [
    TYPESCRIPT_ES,
    REPOSITORY_SECRETLINT,
    REPOSITORY_GITLEAKS,
    COPYPASTE_JSCPD,
    SPELL_CSPELL,
    JSON_JSONLINT,
    YAML_PRETTIER,
  ]

TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
TYPESCRIPT_ES_ARGUMENTS: --fix

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: false

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# All available cores are used by default. If there are too many, you need
# to decrease the number of used cores in order to enhance performances
PARALLEL_PROCESS_NUMBER: 1

# When set to false, only new or edited files will be parsed for validation.
VALIDATE_ALL_CODEBASE: false

DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL

PRINT_ALPACA: false